[package]
authors = ["Taylor C. Richberger <taywee@gmx.com>"]
description = "A brace expansion plugin compatible with Bash for nushell"
repository = "https://github.com/Taywee/nu-plugin-bexpand"
edition = "2021"
license = "MPL-2.0"
name = "nu-plugin-bexpand"
categories = ["command-line-interface", "parser-implementations"]
keywords = ["parser", "shell", "template", "string"]
readme = "README.md"
version = "1.1.1"

[dependencies]
bexpand = "1.1.1"
nu-plugin = "0.81.0"
nu-protocol = { version = "0.81.0", features = ["plugin"] }

